#!/bin/bash
docker run \
    -it --gpus all \
    -u $(id -u):$(id -g) \
    -v /etc/shadow:/etc/shadow:ro \
    -v /etc/passwd:/etc/passwd:ro \
    -v /etc/group:/etc/group:ro \
    -v $PWD:$PWD \
    -w $PWD \
    tfdocker-example /bin/bash
